name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          docker build -t my-app .
          docker run -p 8080:8080 my-app

      - name: Run tests
        run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Docker to Cloud (example AWS)
        run: |
          aws ecr create-repository --repository-name my-app
          docker tag my-app:latest <aws_account_id>.dkr.ecr.<region>.amazonaws.com/my-app:latest
          docker push <aws_account_id>.dkr.ecr.<region>.amazonaws.com/my-app:latest
